it('Buy an Item', () => {
    cy.visit('https://juice-shop.herokuapp.com')
    cy.get('.close-dialog > .mat-button-wrapper').click()

    cy.get('#navbarAccount > .mat-button-wrapper').click()
    cy.get('.cc-btn').click()
    cy.get('#navbarLoginButton').click()
    cy.get('#email').type('burpikxdkngyaynylv@bbitq.com')
    cy.get('#password').type('12345')
    cy.get('#loginButton > .mat-button-wrapper').click()
    cy.get('[style="left: 0px; width: calc(50% - 15px); margin-top: 0px; padding-top: calc(50% - 15px);"] > .mat-grid-tile-content > .mat-card > [style="display: flex; justify-content: center;"] > .mat-focus-indicator').click()
    cy.get('.mat-toolbar-row > .mat-focus-indicator.ng-star-inserted').click()
    cy.get('#checkoutButton').click()
    cy.get('.mat-radio-outer-circle').click()
    cy.get('.btn-next').click()
    cy.get('#mat-radio-42 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click()
    cy.get('.nextButton').click()
    cy.get('.mat-radio-outer-circle').click()
    cy.get('.nextButton').click()
    cy.get('#checkoutButton').click()
})